name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=3.7.1
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.4.0
  - attrs=23.1.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - bleach=6.0.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - colorama=0.4.4
  - conda=4.14.0
  - conda-content-trust=0.1.1
  - conda-package-handling=1.8.1
  - conda-package-streaming=0.7.0
  - cryptography=36.0.0
  - cycler=0.11.0
  - dbus=1.13.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - expat=2.2.10
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.3
  - importlib-metadata=6.8.0
  - importlib_resources=6.0.1
  - ipykernel=5.5.5
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - jedi=0.19.0
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.14
  - jsonschema=4.17.3
  - jupyter_client=7.0.6
  - jupyter_core=5.3.1
  - jupyter_server=1.24.0
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.10.3
  - kiwisolver=1.4.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.14
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.6
  - mistune=3.0.1
  - munkres=1.1.4
  - nb_conda_kernels=2.3.1
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert-core=7.8.0
  - nbformat=5.9.2
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - notebook=6.5.5
  - notebook-shim=0.2.3
  - numpy=1.20.3
  - olefile=0.46
  - openssl=1.1.1v
  - packaging=21.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=21.2.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - prometheus_client=0.17.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycosat=0.6.3
  - pycparser=2.21
  - pygments=2.16.1
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.0
  - python_abi=3.9
  - pytz=2023.3.post1
  - pyzmq=19.0.2
  - qt=5.9.7
  - readline=8.1.2
  - requests=2.27.1
  - ruamel_yaml=0.15.100
  - send2trash=1.8.2
  - setuptools=61.2.0
  - sip=4.19.13
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.38.2
  - stack_data=0.6.2
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.11
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.1
  - tqdm=4.63.0
  - traitlets=5.9.0
  - typing_extensions=4.7.1
  - urllib3=1.26.8
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.6.2
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.12
  - zstandard=0.15.2
  - zstd=1.4.9
  - pip:
    - pandas==2.0.0
    - qmhub==1.0.0+171.g8816a6c.dirty
    - scipy==1.7.1
    - typing-extensions==4.3.0
    - tzdata==2023.3
