###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'Richard Van'
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2024'


extensions = [
        'sphinx_togglebutton', 
        'sphinx_copybutton', 
        'sphinx_thebe', 
        'sphinx_external_toc', 
        'sphinx.ext.intersphinx', 
        'myst_parser',
        'sphinx_design', 
        'sphinx_book_theme', 
        'pydata_sphinx_theme', 
        'sphinx_jupyterbook_latex', 
]

source_suffix = {
    '.rst': 'restructuredtext',
    '.txt': 'markdown',
    # '.md': 'markdown',
}

html_theme = 'pydata_sphinx_theme'
html_baseurl = 'https://van-richard.github.io/CodingNotes/'
html_title = 'CodingNotes'
html_static_path = ['_static/']
html_favicon = '_static/images/van-codingnotes.png'
html_css_path = ['assets/custom.css']


html_sourcelink_suffix = ''
html_sidebar: {
    "**": ['sidebar-nav-bs'],
    "index": ['sidebar-nav-bs'],
    }

html_theme_options = {
    "logo": {
        'text': 'CodingNotes',
        "image_light": "_static/images/van-abstract-y-light.svg",
        "image_dark": "_static/images/van-abstract-y-dark.svg",
    },
    
    "pygment_light_style": "lovelace",
    "pygment_dark_style": "inkpot",
    'article_header_start': ['breadcrumbs'],
    "secondary_sidebar_items": {
        "**": ["page-toc", "sourcelink"],
    },
    "navbar_align": "left",
    'navbar_start': 'navbar-logo',
    'navbar_center': 'navbar-nav',
    'navbar_end': 'navbar-icon-links',
    "icon_links_label": ("Quick Links"),
    "icon_links": [
        {
            "name": "Google Scholar",
            "url": "https://scholar.google.com/citations?user=YQmlIIwAAAAJ&hl=en",
            "icon": "fab fa-google",
        },
        {
            "name": "GitHub",
            "url": "https://github.com/van-richard",
            "icon": "fa-brands fa-square-github",
        },
        {
            "name": "Twitter",
            "url": "https://twitter.com/OMGITSvanADIUM",
            "icon": "fa-brands fa-square-twitter",
        },
        {
            "name": "Linkedin",
            "url": "https://linkedin.com/van-richard",
            "icon": "fa-brands fa-linkedin",
        },
    ],

    'navbar_persistent': ['theme-switcher', 'search-button-field'],
    "show_nav_level": 1,
    "show_toc_level": 1,
    "header_links_before_dropdown": 7,
    'search_bar_text': 'Search mee!!', 
    # 'check_switcher': True,
    }
#latex_engine = 'pdflatex'

myst_enable_extensions = [
        'amsmath', 'colon_fence', 
        'deflist', 'dollarmath', 
        'html_admonition', 
        'html_image', 'linkify', 
        'replacements', 'smartquotes', 
        'substitution', 'tasklist'
]

myst_url_schemes = [
        'mailto', 
        'http', 
        'https'
]

nb_execution_allow_errors = False
nb_execution_cache_path = ''
nb_execution_excludepatterns = []
#nb_execution_in_temp = False
#nb_execution_mode = 'auto'
#nb_execution_timeout = 30
#nb_output_stderr = 'show'

numfig = True
# pygments_style = 'sphinx'
suppress_warnings = ['myst.domains']
use_jupyterbook_latex = True
# use_multitoc_numbering = True

external_toc_exclude_missing = True
external_toc_path = '_toc.yml'

exclude_patterns = [
        '**.ipynb_checkpoints', 
        '.DS_Store', '.git', '.gitignore',
        '.vscode', 'Thumbs.db', 
        '_build', '_static', 'build.sh', 
        'drafts/', 'requirements.txt', 'bak'
]
