# The configurations that used for the recording, feel free to edit them
config:

  # Specify a command to be executed
  # like `/bin/bash -l`, `ls`, or any other commands
  # the default is bash for Linux
  # or powershell.exe for Windows
  command: null
  
  # Specify the current working directory path
  # the default is the current working directory path
  cwd: /Users/van
  
  # Export additional ENV variables
  env:
    recording: null
  
  # Explicitly set the number of columns
  # or use `auto` to take the current
  # number of columns of your shell
  cols: 67
  
  # Explicitly set the number of rows
  # or use `auto` to take the current
  # number of rows of your shell
  rows: 9
  
  # Amount of times to repeat GIF
  # If value is -1, play once
  # If value is 0, loop indefinitely
  # If value is a positive number, loop n times
  repeat: 0
  
  # Quality
  # 1 - 100
  quality: 100 
  # Delay between frames in ms
  # If the value is `auto` use the actual recording delays
  frameDelay: auto
  
  # Maximum delay between frames in ms
  # Ignored if the `frameDelay` isn't set to `auto`
  # Set to `auto` to prevent limiting the max idle time
  maxIdleTime: 2000
  
  # The surrounding frame box
  # The `type` can be null, window, floating, or solid`
  # To hide the title use the value null
  # Don't forget to add a backgroundColor style with a null as type
  frameBox:
    type: window
    title: Terminal
    style:
      backgroundColor: black
      border: 0px black solid
      # boxShadow: none
      # margin: 0px
  
  # Add a watermark image to the rendered gif
  # You need to specify an absolute path for
  # the image on your machine or a URL, and you can also
  # add your own CSS styles
  watermark:
    imagePath: null
    style:
      position: absolute
      right: 15px
      bottom: 15px
      width: 100px
      opacity: 0.9
  
  # Cursor style can be one of
  # `block`, `underline`, or `bar`
  cursorStyle: block
  
  # Font family
  # You can use any font that is installed on your machine
  # in CSS-like syntax
  fontFamily: "Monaco, Lucida Console, Ubuntu Mono, Monospace"
  
  # The size of the font
  fontSize: 12
  
  # The height of lines
  lineHeight: 1
  
  # The spacing between letters
  letterSpacing: 0
  
  # Theme
  theme:
    background: "transparent"
    foreground: "#afafaf"
    cursor: "#c7c7c7"
    black: "#232628"
    red: "#fc4384"
    green: "#b3e33b"
    yellow: "#ffa727"
    blue: "#75dff2"
    magenta: "#ae89fe"
    cyan: "#708387"
    white: "#d5d5d0"
    brightBlack: "#626566"
    brightRed: "#ff7fac"
    brightGreen: "#c8ed71"
    brightYellow: "#ebdf86"
    brightBlue: "#75dff2"
    brightMagenta: "#ae89fe"
    brightCyan: "#b1c6ca"
    brightWhite: "#f9f9f4"
  
# Records, feel free to edit them
records:
  - delay: 0
    content: "\e]7;file://vans-MacBook-Pro.local/Users/van\e]vans-MacBook-Pro:~ van$ "
  - delay: 150
    content: p
  - delay: 150
    content: w
  - delay: 150
    content: d
  - delay: 150
    content: "\r\n/Users/van/\e]7;file://vans-MacBook-Pro.local/Users/van\avans-MacBook-Pro:~ van$ "
  - delay: 2000
    content: e
  - delay: 150
    content: c
  - delay: 150
    content: h
  - delay: 150
    content: o
  - delay: 150
    content: ' '
  - delay: 150
    content: '"'
  - delay: 150
    content: H
  - delay: 150
    content: e
  - delay: 150
    content: l
  - delay: 150
    content: l
  - delay: 150
    content: o
  - delay: 150
    content: ' '
  - delay: 150
    content: W
  - delay: 150
    content: o
  - delay: 150
    content: r
  - delay: 150
    content: l
  - delay: 150
    content: d
  - delay: 150
    content: '"'
  - delay: 150
    content: "\r\nHello World\r\n\e]7;file://vans-MacBook-Pro.local/Users/van\avans-MacBook-Pro:~ van$ "
  - delay: 2000
    content: e
  - delay: 150
    content: c
  - delay: 150
    content: h
  - delay: 150
    content: o
  - delay: 150
    content: ' '
  - delay: 150
    content: '"'
  - delay: 150
    content: '2'
  - delay: 150
    content: ' '
  - delay: 150
    content: +
  - delay: 150
    content: ' '
  - delay: 150
    content: '2'
  - delay: 150
    content: '"'
  - delay: 150
    content: ' '
  - delay: 150
    content: '|'
  - delay: 150
    content: ' '
  - delay: 150
    content: b
  - delay: 150
    content: c
  - delay: 150
    content: ' '
  - delay: 150
    content: '-'
  - delay: 150
    content: l
  - delay: 150
    content: "\r\n"
  - delay: 500
    content: "4\r\n\e]7;file://vans-MacBook-Pro.local/Users/van\avans-MacBook-Pro:~ van$ "
  - delay: 2000
    content: e
  - delay: 150
    content: c
  - delay: 150
    content: h
  - delay: 150
    content: o
  - delay: 150
    content: ' '
  - delay: 150
    content: $
  - delay: 150
    content: S
  - delay: 150
    content: H
  - delay: 150
    content: E
  - delay: 150
    content: L
  - delay: 150
    content: L
  - delay: 150
    content: "\r\n/bin/bash\r\n\e]7;file://vans-MacBook-Pro.local/Users/van/\avans-MacBook-Pro:gif van$ "
  - delay: 2000
    content: 'Y'
  - delay: 150
    content: E
  - delay: 150
    content: E
  - delay: 150
    content: "\r\nbash: HAW\r\n\e]7;file://vans-MacBook-Pro.local/Users/van\avans-MacBook-Pro:~ van$ "
